Update platformio.ini
Latest PlatformIO on Windows doesn't support `@` type of versioning, it requires commit hash instead. It produces error during build:
```
PackageException: Package version 7.2.1+sha.7946ebe doesn't satisfy requirements 7.0.4 based on PackageMetadata <type=library name=ArduinoJson version=7.2.1+sha.7946ebe spec={'owner': None, 'id': None, 'name': 'ArduinoJson', 'requirements': '7.0.4', 'uri': 'git+https://github.com/bblanchon/ArduinoJson.git'}
```